### ISSUE TITLE
Add option to create certificate for all domains and subdomains

### ISSUE THREAD

**Issue by brianread108** [reetp/smeserver-letsencrypt#10]
Many servers will want all the domains and subdomains that the server resolves to be certified, so adding a "Select all" would make this very much easier than having to specifically name each one.

**Comment by reetp** [comment]
As per our discussions I'll look at implementing this PDQ.

Only thought is will a large amount of domains overwhelm their server ? Not sure if there are any restrictions ?

**Comment by danb35** [comment]
LE has a limit of no more than 100 hostnames/cert, so I doubt that would be an issue in most deployments.

Might want to consider, though, what "select all" should include.  Should it be every hostname and domain the system knows?  That seems overly-broad, since you'll frequently set up hostnames for other hosts on your LAN, and sometimes even for remote hosts.  It should, I'd think, limit only to hosts where HostType=Self.

**Comment by reetp** [comment]
Thanks for that info Dan

We can count items and issue a warning if the limit is exceeded. I know someone running 80 domains I think so it could be a consideration for some.

The host=self is a good suggestion.

Will have a look at it and see what I can work out.

Any more ideas on the subject welcome

**Comment by brianread108** [comment]
yes, i agree that host=self makes sense.

**Comment by reetp** [comment]
Host=self us ok.

What key for domain from db domains ?

**Comment by danb35** [comment]
Nameservers=localhost, maybe?

**Comment by beastybeast** [comment]
I have seen that a lot of domains/host can create a long chain where the possibility of just one of them have a problem will break the execution - this have to be addressed first.

But it is a logical option to have host=self or similar effect

**Comment by danb35** [comment]
True--the greater the number of hostnames, the greater the chance for failure.  If any of the requested hostnames fails, no certificate will be issued.  So long as SME is designed using a single cert/key, though, it's necessary.

The alternative is to use SNI and have multiple certs (one cert per domain would seem to make the most sense, but no doubt other arrangements could be used), as suggested by https://bugs.contribs.org/show_bug.cgi?id=9196#c19.  This would require some pretty significant changes to the way SME does things, and I'm not sure the benefits would be worth the work.  It would mean, however, that an error with one domain wouldn't affect issuing certificates for other domains.

**Comment by reetp** [comment]
Funny how you think at 35,000 feet :-)

I suggest (for now) 'all' means an enabled domain and any of its hosts that are self

So

db domain setprop leysencrypt status enabled hosts all

Just trying to cut down the likelihood of bad hosts/domains being included. A 'fire once' key makes that simpler.

As a lot of this is not for beginners nor the faint hearted I am not spending too much time making it completely bomb proof. Jean Philippr intends to write a full implementation to look at multi certs etc.

This is bandaid to simplify it a bit for the time being and learn a few lessons (which we have)

Above is easy to do if you agree it is the way to go

**Comment by reetp** [comment]
A number of issues with 'all' that came to me when trying to code this.

If we only create a cert for self/local machines it won't then create for a remote machine where you want to send it via a hook script.

So this makes it a tad more tricky.....

I was thinking of making a switch with varying statuses 

e.g. all, local, remote, both, domains,hosts

We could also specify a 'hostype' as well e.g www,ftp,imap,all

So you could specify 'www,mail' to get all hosts that are www and mail

Yes we could make all mean ALL regardless, but does it want the option of refining a bit ?

Any thoughts on this ?

**Comment by reetp** [comment]
Fixed in 0.2-6
